spring.application.name=API-Desafio-de-Chat-Virtual

spring.datasource.url=jdbc:postgresql://localhost:5433/apichat
spring.datasource.username=matheusps
spring.datasource.password=M@t372128

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret= 65bab7096574c00a01eba8285c4024a9ea62795b945d6edfe8f5a6254935fd1234567890
jwt.expiration= 86400000