version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-chat
    environment:
      POSTGRES_USER: matheusps
      POSTGRES_PASSWORD: M@t372128
      POSTGRES_DB: apichat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: